### ISSUE TITLE
Need to add http://download.controlsystemstudio.org/updates/4.x repo?

### ISSUE THREAD

**Issue by richardfearn** [ControlSystemStudio/org.csstudio.sns#1]
I'm looking at what other sites are doing with respect to site-specific features/products and wanted to build the SNS plugins/features/products. However I think a `download.controlsystemstudio.org` repo needs to be added to the top-level POM so that bundles like `org.csstudio.platform.libs.jms` can be found.

**Comment by kasemir** [comment]
I build the sources as they are with the 'csstudio.local.repo' approach described here: http://cs-studio.sourceforge.net/docbook/ch04.html

**Comment by richardfearn** [comment]
Seems to work now, with no modifications required.
